# Generated by Django 4.2.4 on 2023-08-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=20)),
                ('book_cost', models.IntegerField()),
                ('book_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Avtors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avtor_name', models.CharField(default='', max_length=23)),
                ('avtor_bday', models.DateField()),
                ('avtor_books_created_name', models.CharField(default='', max_length=23)),
                ('avtor_date_of_die', models.DateField()),
                ('Books_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books_and_avtors.books')),
            ],
        ),
    ]
